"""
AI Content Detector Service

Uses Vertex AI (Gemini) to detect AI-generated content in images and videos.
This is a separate module from deepfake detection.
"""
import os
import json
import base64
from typing import Dict, Any, Optional
import logging

logger = logging.getLogger(__name__)


from api.core.config import settings

class AIContentDetector:
    """
    AI-generated content detector using Vertex AI.
    
    Uses Gemini 2.0 Flash to analyze media and determine
    if it was generated by AI.
    """
    
    def __init__(
        self,
        project_id: Optional[str] = None,
        location: str = "us-central1",
        credentials_file: Optional[str] = None
    ):
        """
        Initialize the AI content detector.
        
        Args:
            project_id: Google Cloud project ID
            location: Vertex AI location
            credentials_file: Path to service account JSON
        """
        # Use settings (loaded from .env) as default if args not provided
        self.project_id = project_id or settings.GOOGLE_CLOUD_PROJECT or os.getenv("GOOGLE_CLOUD_PROJECT", "")
        self.location = location or settings.VERTEX_AI_LOCATION or os.getenv("VERTEX_AI_LOCATION", "us-central1")
        self.credentials_file = credentials_file or settings.GOOGLE_APPLICATION_CREDENTIALS or os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")
        
        self._initialized = False
        self._model = None
    
    def initialize(self) -> bool:
        """
        Initialize Vertex AI connection.
        
        Returns:
            True if successful, False otherwise
        """
        if self._initialized:
            return True
        
        # Check if GCP is configured
        if not self.project_id:
            logger.warning("⚠️ AI Content Detector disabled - GOOGLE_CLOUD_PROJECT not set")
            return False
        
        if not self.credentials_file or not os.path.exists(self.credentials_file):
            logger.warning("⚠️ AI Content Detector disabled - GCP credentials file not found")
            return False
            
        # Explicitly set the environment variable for Google Auth library
        os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = self.credentials_file
        
        try:
            import vertexai
            from vertexai.generative_models import GenerativeModel
            
            # Initialize Vertex AI
            vertexai.init(project=self.project_id, location=self.location)
            self._model = GenerativeModel("gemini-2.0-flash-001")
            self._initialized = True
            
            logger.info(f"✅ Vertex AI initialized - Project: {self.project_id}")
            return True
            
        except Exception as e:
            logger.warning(f"⚠️ AI Content Detector disabled - Vertex AI init failed: {e}")
            return False
    
    @property
    def is_initialized(self) -> bool:
        """Check if Vertex AI is initialized."""
        return self._initialized
    
    async def analyze(
        self,
        file_data: bytes,
        mime_type: str = "image/jpeg"
    ) -> Dict[str, Any]:
        """
        Analyze media for AI-generated content.
        
        Args:
            file_data: Raw file bytes
            mime_type: MIME type of the file
            
        Returns:
            Detection result with verdict, confidence, explanation
        """
        if not self._initialized:
            if not self.initialize():
                return {
                    "success": False,
                    "error": "AI Content Detection requires GCP credentials. Set GOOGLE_CLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS environment variables."
                }
        
        try:
            from vertexai.generative_models import Part
            
            media_type = "image" if mime_type.startswith("image/") else "video"
            
            prompt = f"""
Analyze this {media_type}. Respond ONLY in JSON:
{{
  "verdict": "AI_GENERATED" | "LIKELY_REAL" | "UNCERTAIN",
  "confidence": 0-100,
  "explanation": "text",
  "indicators": ["list"]
}}
"""
            
            part = Part.from_data(file_data, mime_type=mime_type)
            response = self._model.generate_content([prompt, part])
            
            # Parse response
            raw = response.text.strip()
            if raw.startswith("```"):
                raw = raw.replace("```json", "").replace("```", "").strip()
            
            result = json.loads(raw)
            
            return {
                "success": True,
                "result": result,
                "media_type": media_type
            }
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse AI response: {e}")
            return {
                "success": False,
                "error": f"Invalid response format: {str(e)}"
            }
        except Exception as e:
            logger.error(f"AI analysis failed: {e}")
            return {
                "success": False,
                "error": str(e)
            }
    
    async def analyze_base64(
        self,
        base64_data: str,
        mime_type: str = "image/jpeg"
    ) -> Dict[str, Any]:
        """
        Analyze base64-encoded media.
        
        Args:
            base64_data: Base64-encoded file data
            mime_type: MIME type of the file
            
        Returns:
            Detection result
        """
        try:
            file_data = base64.b64decode(base64_data)
            return await self.analyze(file_data, mime_type)
        except Exception as e:
            return {
                "success": False,
                "error": f"Base64 decode failed: {str(e)}"
            }
    
    def get_status(self) -> Dict[str, Any]:
        """Get detector status."""
        return {
            "initialized": self._initialized,
            "project": self.project_id or "not_set",
            "location": self.location,
            "model": "gemini-2.0-flash-001" if self._initialized else None
        }


# Global instance
ai_detector = AIContentDetector()
